openapi: 3.0.0
info:
  version: 0.0.1
  title: Inventory Tracker API
  description: The API that the Inventory Tracker clients communicate with

components:
  schemas:
    Item:
      allOf:
        - $ref: '#/components/schemas/PartialItem'
        - type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
            quantity:
              type: integer
          required:
            - id
            - name
            - quantity
    PartialItem:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
      required:
        - name
        - quantity
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: x-api-key
  responses:
    NoApiKey:
      description: a valid api key was not provided

security:
  - ApiKey: []

paths:
  /list:
    get:
      description: returns items in the list
      parameters:
        - name: offset
          in: query
          description: get items from this offset
          default: 0
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: limits the number of items returned
          default: 25
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: successfully returned items in the list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '401':
          $ref: '#/components/responses/NoApiKey'
        '413':
          description: too many items requested
    put:
      description: adds items to the list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PartialItem'
      responses:
        '200':
          description: item successfully added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '401':
          $ref: '#/components/responses/NoApiKey'
        '403':
          description: one or more of the partial items were invalid
        '413':
          description: attempted to add too many items
    patch:
      description: replaces items in the list
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: all replacements were successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '401':
          $ref: '#/components/responses/NoApiKey'
        '403':
          description: one or more of the items are invalid
        '404':
          description: one or more items being replaced were not found
        '413':
          description: attempted to replace too many items
    delete:
      description: removes items in the list
      parameters:
        - name: items
          in: query
          schema:
            type: array
            items:
              type: integer
      responses:
        '204':
          description: item successfully removed
        '401':
          $ref: '#/components/responses/NoApiKey'
        '404':
          description: no item found to delete
        '413':
          description: attempted to delete too many items
  /report:
    get:
      description: returns a report on the list over a given period
      responses:
        '401':
          $ref: '#/components/responses/NoApiKey'
        '501':
          description: not implemented in this version
