swagger: '2.0'
info:
  version: 0.0.4
  title: Inventory Tracker API
  description: The API that the Inventory Tracker clients communicate with

securityDefinitions:
  ApiKey:
    type: apiKey
    in: header
    name: X-API-Key

security:
- ApiKey: []

x-amazon-apigateway-request-validators:
  both: 
    validateRequestBody: true
    validateRequestParameters: true

x-amazon-apigateway-api-key-source: 'HEADER'
x-amazon-apigateway-request-validator: 'both'

definitions:

  Item:
    allOf:
    - "$ref": "#/definitions/PartialItem"
    - type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        quantity:
          type: integer
      required:
      - id
      - name
      - quantity

  PartialItem:
    type: object
    properties:
      name:
        type: string
      quantity:
        type: integer
    required:
    - name
    - quantity
  NoApiKey:
    description: a valid api key was not provided

paths:

  "/list":

    get:
      description: returns items in the list
      parameters:
      - name: offset
        in: query
        description: get items from this offset
        default: 0
        required: false
        type: integer
      - name: limit
        in: query
        description: limits the number of items returned
        default: 25
        required: false
        type: integer
      responses:
        '200':
          description: successfully returned items in the list
          schema:
            type: array
            items:
              "$ref": "#/definitions/Item"
        '401':
          "$ref": "#/definitions/NoApiKey"
        '413':
          description: too many items requested
      x-amazon-apigateway-integration: # TODO

    post:
      description: adds items to the list
      parameters:
      - required: true
        name: body
        in: body
        schema:
          type: array
          items:
            "$ref": "#/definitions/PartialItem"
      responses:
        '200':
          description: item successfully added
          schema:
            type: array
            items:
              "$ref": "#/definitions/Item"
        '401':
          "$ref": "#/definitions/NoApiKey"
        '403':
          description: one or more of the partial items were invalid
        '413':
          description: attempted to add too many items
      x-amazon-apigateway-integration: # TODO

    put:
      description: replaces items in the list
      parameters:
      - name: body
        in: body
        schema:
          type: array
          items:
            "$ref": "#/definitions/Item"
      responses:
        '200':
          description: all replacements were successful
          schema:
            type: array
            items:
              "$ref": "#/definitions/Item"
        '401':
          "$ref": "#/definitions/NoApiKey"
        '403':
          description: one or more of the items are invalid
        '404':
          description: one or more items being replaced were not found
        '413':
          description: attempted to replace too many items
      x-amazon-apigateway-integration: # TODO

    delete:
      description: removes items in the list
      parameters:
      - name: items
        in: query
        type: array
        items:
          type: integer
      responses:
        '204':
          description: item successfully removed
        '401':
          "$ref": "#/definitions/NoApiKey"
        '404':
          description: no item found to delete
        '413':
          description: attempted to delete too many items
      x-amazon-apigateway-integration: # TODO

  "/report":

    get:
      description: returns a report on the list over a given period
      parameters: []
      responses:
        '401':
          "$ref": "#/definitions/NoApiKey"
        '501':
          description: not implemented in this version
      x-amazon-apigateway-integration: # TODO

